version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
    cooldown:
      default-days: 5
      exclude:
        - '@grafana/plugin-e2e'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      npm-all:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(ci)'
    groups:
      actions-all:
        patterns:
          - '*'

  - package-ecosystem: gomod
    directory: '/'
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      go-all:
        patterns:
          - '*'
