version: "2"

linters:
  enable:
    - bodyclose
    - gocritic
    - gocyclo
    - misspell
    - revive
    - unconvert
    - unparam
  settings:
    gocyclo:
      min-complexity: 35
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: unreachable-code
  exclusions:
    paths:
      - node_modules
    rules:
      - linters: [errcheck]
        path: _test\.go
