{
 "title": "Operasjonelt Ekstern Tjeneste",
 "tags": [
  "ops",
  "nais"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": "dev,prod" },
   { "name": "tjenester", "label": "tjeneste", "query": "login.microsoftonline.com" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "loki", "query": "loki" },
   { "name": "tempo", "query": "tempo" },
   {
    "name": "services",
    "label": "apps",
    "query": {
     "query": "query_result(count by(service_name) (traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", server_address=\"$tjenester\"}) or count by(service_name) (traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", http_host=\"$tjenester:443\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request rate for $tjenester",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", server_address=\"$tjenester\", status_code=~\"STATUS_CODE_OK|STATUS_CODE_UNSET\"}[$__rate_interval])) or vector(0)\n  +\n  sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", http_host=\"$tjenester:443\", status_code=~\"STATUS_CODE_OK|STATUS_CODE_UNSET\"}[$__rate_interval])) or vector(0)\n)",
     "legendFormat": "STATUS_CODE_OK|STATUS_CODE_UNSET"
    },
    {
     "expr": "(\n  sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", server_address=\"$tjenester\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval])) or vector(0)\n  +\n  sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", http_host=\"$tjenester:443\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval])) or vector(0)\n)",
     "legendFormat": "STATUS_CODE_ERROR"
    }
   ]
  },
  {
   "title": "Request Latency for $tjenester",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum by (le) (\n    rate(traces_spanmetrics_latency_bucket{\n      span_kind=\"SPAN_KIND_CLIENT\", \n      server_address=\"$tjenester\"\n    }[$__rate_interval])\n    or\n    rate(traces_spanmetrics_latency_bucket{\n      span_kind=\"SPAN_KIND_CLIENT\", \n      http_host=\"$tjenester:443\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "latency p99"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum by (le) (\n    rate(traces_spanmetrics_latency_bucket{\n      span_kind=\"SPAN_KIND_CLIENT\", \n      server_address=\"$tjenester\"\n    }[$__rate_interval])\n    or\n    rate(traces_spanmetrics_latency_bucket{\n      span_kind=\"SPAN_KIND_CLIENT\", \n      http_host=\"$tjenester:443\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "latency p95"
    }
   ]
  },
  {
   "title": "Konsumenter",
   "type": "table",
   "description": "Liste over applikasjoner som konsumerer denne tjenesten",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "    (\n      sum by (service_name, service_namespace) (\n        rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", server_address=\"$tjenester\"}[$__rate_interval])\n      ) or vector(0)\n      +\n      sum by (service_name, service_namespace) (\n        rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", http_host=\"$tjenester:443\"}[$__rate_interval])\n      ) or vector(0)\n    )"
    },
    {
     "expr": "    (\n      sum by (service_name, service_namespace) (\n        rate(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",span_kind=\"SPAN_KIND_CLIENT\", server_address=\"$tjenester\"}[$__rate_interval])\n      ) or vector(0)\n      +\n      sum by (service_name, service_namespace) (\n        rate(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",span_kind=\"SPAN_KIND_CLIENT\", http_host=\"$tjenester:443\"}[$__rate_interval])\n      ) or vector(0)\n    )"
    }
   ]
  },
  {
   "title": "Siste Feilede Traces",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "filters": [
      {
       "id": "6adceae0",
       "operator": "=",
       "scope": "span",
       "tag": "http.host",
       "value": [ "$tjenester" ]
      },
      {
       "id": "status",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "value": "error",
       "valueType": "keyword"
      },
      {
       "id": "deb41747",
       "operator": "=",
       "scope": "span",
       "tag": "http.server_name",
       "value": [ "$tjenester" ],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "spinnsyn-frontend" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name =~ \"$services\" && status = error && (span.server.address = \"$tjenester\" || span.http.host = \"$tjenester:443\")}",
     "tableType": "traces"
    }
   ]
  }
 ]
}