{
 "title": "Operasjonelt Dashboard",
 "tags": [
  "ops",
  "nais"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Miljø", "query": "dev,prod,prod-fss,prod-gcp" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "prometheus_fss", "query": "prometheus" },
   { "name": "loki", "query": "loki" },
   { "name": "tempo", "query": "tempo" },
   {
    "name": "tjenester",
    "label": "eksterne tjenester",
    "query": "idporten.no,graph.microsoft.com,login.microsoftonline.com,maskinporten.no,matrikkel.no,inntekt.api.skatteetaten.no,inntekthendelser.api.skatteetaten.no,ws.nhn.no,www.altinn.no,api.prod.spk.no,api.helsedirektoratet.no,api.husbanken.no,api.kartverket.no"
   },
   {
    "name": "apps",
    "label": "interne applikasjoner",
    "query": "aareg-services-nais,aktivitetsplan,arbeidsrettet-dialog,arbeid-og-inntekt,arbeidssokerregistrering,behandlingsflyt,digdir-krr-proxy,ditt-sykefravaer,ditt-sykefravaer-backend,dokprod,dokarkiv,dp-behandling,dp-rapportering-personregister,dp-saksbehandling,dp-saksbehandling-frontend,ebms-provider,entra-proxy,etterlatte-behandling,familie-ba-sak,familie-ef-infotrygd,flex-sykmeldinger-backend,foreldrepengesoknad,fp-frontend,frikortkjernenproxy,frikortsak,frikortvedtak,gosys,gosys-oppgavebehandling-api,innsending-api,inst2,ikomp,istilgangskontroll,k9-sak,meldekort,meldekort-api,meldekort-backend,meldekort-frontend,meldekortkontroll-api,mine-saker-api,modiacontextholder,modiapersonoversikt,modiapersonoversikt-api,nom-api,nav-dekoratoren-api,nav-enonicxp-frontend,navno-search-frontend,norg2,notat-administrasjon,oppgave,pam-search-api,pam-stillingsok,pdl-api,pdl-pip-api,pdl-tilgangsstyring,pdl-web,pensjonskalkulator-backend,pensjon-pen,pensjon-penny,pensjon-psak,pensjon-regler,populasjonstilgangskontroll,rekrutteringsbistand-frontend,rekrutteringsbistand-kandidat-api,rekrutteringsbistand-stilling-api,saf,safselvbetjening,sigrun,saksbehandling,skjemautfylling,skjermede-personer-pip,sosialhjelp-innsyn,sosialhjelp-innsyn-api,sosialhjelp-modia,sosialhjelp-modia-api,sosialhjelp-soknad-api,sokos-oppdrag,sokos-skattekort,sokos-pdl-proxy,sokos-utbetalingsportalen,speil,syfooversiktsrv,\nsyfomodiaperson,sykepengesoknad,veilarbarena,veilarbaktivitet,veilarbdialog,veilarboppfolging,veilarbpersonflate,wonderwall-idporten"
   },
   {
    "name": "databaser",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total,db_system)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP Response Koder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Response by Status (GCP)",
   "type": "timeseries",
   "description": "Request på tvers av alle nav-applikasjoner fordelt på statuskoder.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status_family) (\n  label_replace(\n    rate(nginx_ingress_controller_requests{}[$__rate_interval]),\n    \"status_family\", \"${1}xx\", \"status\", \"([1-5]).*\"\n  )\n)",
     "legendFormat": "{{status_family}}"
    }
   ]
  },
  {
   "title": "App Response by Status (FSS)",
   "type": "timeseries",
   "description": "Request på tvers av alle nav-applikasjoner fordelt på statuskoder.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status_family) (\n  label_replace(\n    rate(nginx_ingress_controller_requests{}[$__rate_interval]),\n    \"status_family\", \"${1}xx\", \"status\", \"([1-5]).*\"\n  )\n)",
     "legendFormat": "{{status_family}}"
    }
   ]
  },
  { "title": "Interne Applikasjoner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$apps",
   "type": "stat",
   "description": "Suksess rate mot interne applikasjoner målt fra applikasjonen med OpenTelemetry Auto-Instrumentering. I noen tilfeller vil 404 bli talt som feil.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "repeat": "apps",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  (\n    (\n      sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$apps\", status_code=~\"STATUS_CODE_OK|STATUS_CODE_UNSET\"}[$__rate_interval])) or vector(0)\n    )\n    /\n    (\n      clamp_min(\n        sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$apps\"}[$__rate_interval])) or vector(0),\n        1e-10\n      )\n    )\n  ) > 0\n) \n* \n(\n  (\n    sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$apps\", status_code=~\"STATUS_CODE_OK|STATUS_CODE_UNSET\"}[$__rate_interval])) or vector(0)\n  )\n  /\n  (\n    clamp_min(\n      sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$apps\"}[$__rate_interval])) or vector(0),\n      1e-10\n    )\n  )\n) \nor\nvector(1)",
     "legendFormat": "$tjenester"
    }
   ]
  },
  { "title": "Eksterne Tjenestekall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "$tjenester",
   "type": "stat",
   "description": "Suksess rate mot eksterne tjenester målt fra nav sine applikasjoner med OpenTelemetry Auto-Instrumentering. I noen tilfeller vil 404 bli talt som feil.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 70 },
   "repeat": "tjenester",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  (\n    (\n      sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", server_address=\"$tjenester\", status_code=~\"STATUS_CODE_OK|STATUS_CODE_UNSET\"}[$__rate_interval])) or vector(0)\n      +\n      sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", http_host=\"$tjenester:443\", status_code=~\"STATUS_CODE_OK|STATUS_CODE_UNSET\"}[$__rate_interval])) or vector(0)\n    )\n    /\n    (\n      clamp_min(\n        sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", server_address=\"$tjenester\"}[$__rate_interval])) or vector(0)\n        +\n        sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", http_host=\"$tjenester:443\"}[$__rate_interval])) or vector(0),\n        1e-10\n      )\n    )\n  ) > 0\n) \n* \n(\n  (\n    sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", server_address=\"$tjenester\", status_code=~\"STATUS_CODE_OK|STATUS_CODE_UNSET\"}[$__rate_interval])) or vector(0)\n    +\n    sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", http_host=\"$tjenester:443\", status_code=~\"STATUS_CODE_OK|STATUS_CODE_UNSET\"}[$__rate_interval])) or vector(0)\n  )\n  /\n  (\n    clamp_min(\n      sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", server_address=\"$tjenester\"}[$__rate_interval])) or vector(0)\n      +\n      sum(rate(traces_spanmetrics_calls_total{span_kind=\"SPAN_KIND_CLIENT\", http_host=\"$tjenester:443\"}[$__rate_interval])) or vector(0),\n      1e-10\n    )\n  )\n) \nor\nvector(1)",
     "legendFormat": "$tjenester"
    }
   ]
  },
  { "title": "Databaser", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "$databaser",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 83 },
   "repeat": "databaser",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(traces_spanmetrics_calls_total{db_system=\"$databaser\", status_code!=\"STATUS_CODE_ERROR\"}[$__rate_interval]) or vector(0))\n)\n/\nclamp_min(sum(rate(traces_spanmetrics_calls_total{db_system=\"$databaser\"}[$__rate_interval]) or vector(0)), 1e-10)",
     "legendFormat": "$tjenester"
    }
   ]
  }
 ]
}