-- Minimal init script for the OTel Demo astronomy database
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
CREATE USER astronomy_user WITH PASSWORD 'astronomy_password';
CREATE DATABASE astronomy_db OWNER astronomy_user;
CREATE USER monitoring_user WITH PASSWORD 'monitoring_password';
GRANT pg_monitor TO monitoring_user;

\connect astronomy_db
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

CREATE SCHEMA catalog;
GRANT USAGE ON SCHEMA catalog TO astronomy_user;

CREATE TABLE catalog.products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    picture TEXT,
    price_currency_code TEXT NOT NULL,
    price_units BIGINT NOT NULL,
    price_nanos INT NOT NULL,
    categories TEXT
);

GRANT SELECT ON ALL TABLES IN SCHEMA catalog TO astronomy_user;

INSERT INTO catalog.products (id, name, description, picture, price_currency_code, price_units, price_nanos, categories)
VALUES
    ('OLJCESPC7Z', 'Explorascope', 'Refractor telescope', 'Explorascope.jpg', 'USD', 101, 960000000, 'telescopes'),
    ('66VCHSJNUP', 'Starsense Explorer', 'Smartphone telescope', 'Starsense.jpg', 'USD', 349, 950000000, 'telescopes'),
    ('1YMWWN1N4O', 'Eclipsmart Travel', 'Solar scope', 'Eclipsmart.jpg', 'USD', 129, 950000000, 'telescopes'),
    ('L9ECAV7KIM', 'Lens Cleaning Kit', 'Optics cleaner', 'LensKit.jpg', 'USD', 21, 950000000, 'accessories'),
    ('2ZYFJ3GM2N', 'Roof Binoculars', 'All-around binoculars', 'Binoculars.jpg', 'USD', 209, 950000000, 'binoculars'),
    ('0PUK6V6EV0', 'Solar System Imager', 'Planetary camera', 'Imager.jpg', 'USD', 175, 0, 'accessories'),
    ('LS4PSXUNUM', 'Red Flashlight', '3-in-1 device', 'Flashlight.jpg', 'USD', 57, 80000000, 'accessories'),
    ('9SIQT8TOJO', 'Optical Tube Assembly', 'RASA V2 OTA', 'OTA.jpg', 'USD', 3599, 0, 'telescopes'),
    ('6E92ZMYYFZ', 'Solar Filter', 'EclipSmart filter', 'Filter.jpg', 'USD', 69, 950000000, 'accessories'),
    ('HQTGWGPNH4', 'The Comet Book', '16th-century treatise', 'CometBook.jpg', 'USD', 0, 990000000, 'books');

CREATE SCHEMA reviews;
GRANT USAGE ON SCHEMA reviews TO astronomy_user;

CREATE TABLE reviews.productreviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(16) NOT NULL,
    username VARCHAR(64) NOT NULL,
    description VARCHAR(1024),
    score NUMERIC(2,1) NOT NULL
);

CREATE INDEX product_id_index ON reviews.productreviews (product_id);
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA reviews TO astronomy_user;

INSERT INTO reviews.productreviews (product_id, username, description, score)
VALUES
    ('OLJCESPC7Z', 'stargazer_mike', 'Great telescope for beginners!', '4.5'),
    ('66VCHSJNUP', 'tech_astro', 'StarSense app is revolutionary!', '5.0'),
    ('1YMWWN1N4O', 'solar_viewer', 'Perfect for solar observations!', '5.0');
