# This GitHub Action automates the process of building Grafana plugins.
# (For more information, see https://github.com/grafana/plugin-actions/blob/main/build-plugin/README.md)
name: Release

on:
  push:
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0.

permissions: read-all

jobs:
  release:
    permissions:
      id-token: write
      contents: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          persist-credentials: false

      - uses: grafana/plugin-actions/build-plugin@a66a1c96cdbb176f9cccf10cf23593e250db7cce # ratchet:grafana/plugin-actions/build-plugin@build-plugin/v1.1.0
        # To enable plugin signing, add GRAFANA_ACCESS_POLICY_TOKEN to repository secrets.
        # For private signing, also add GRAFANA_PLUGIN_ROOT_URLS (comma-separated Grafana instance URLs).
        # See: https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin#generate-an-access-policy-token
        with:
          policy_token: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
          sign_root_urls: ${{ secrets.GRAFANA_PLUGIN_ROOT_URLS }}
          attestation: true
